const SERVER_ERROR = 500
const SUCCESS=200
const CREATED = 201
const BAD_REQUEST=400
const NOT_FOUND=404
const NOT_AUTHENTICATED=401
const FORBIDDEN_REQUEST=401
module.exports = {
    SERVER_ERROR,
    CREATED,
    SUCCESS,
    BAD_REQUEST,
    NOT_AUTHENTICATED,
    NOT_FOUND
}